///Author: Payman Rowhani & Artin Rezaie 
///Copyright (C) Artman Systems Inc. 2004-2009

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Net.Mail;

public partial class Admin_CreateAccount : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        Form.DefaultButton = SignUp.UniqueID;
    }

    public bool ValidateUser()
    {
        bool exists = DatabaseUtil.CheckForExistance("User", new string[] { "UserName" }, new string[] { UserName.Text.Trim() });
        return !exists;
    }

    public void SaveUser()
    {
        DatabaseUtil.SaveUserToDB(UserName.Text.Trim(), Password.Text.Trim(),
                            FirstName.Text.Trim(), LastName.Text.Trim(), Email.Text.Trim());
    }

    public void SendMail()
    {
        try
        {
            string to = Email.Text.Trim();
            string body = "Your account has been created.";
            body += "<br />User Name: " + UserName.Text.Trim();
            body += "<br />Password: " + Password.Text.Trim();
            body += "<br /><br />Artman CMS System Administrator.<br />";
            body += "<br /><br />*** This message is generated by system.  Please do not reply to the sender ***.";
            string subject = "CMS Account Created";

            //Prepare mail content, subject, and addresses
            System.Net.Mail.MailMessage myMailMessage = new System.Net.Mail.MailMessage();
            myMailMessage.From = new MailAddress(ConfigurationManager.AppSettings["MailFrom"], ConfigurationManager.AppSettings["MailName"]);
            myMailMessage.To.Add(to);
            myMailMessage.Subject = subject;
            myMailMessage.Body = body;
            myMailMessage.IsBodyHtml = true;

            //Pay attention to the command orders!!!
            System.Net.Mail.SmtpClient mailClient = new System.Net.Mail.SmtpClient(ConfigurationManager.AppSettings["SmtpServer"], Int32.Parse(ConfigurationManager.AppSettings["SmtpServerPort"]));
            mailClient.EnableSsl = true;
            mailClient.UseDefaultCredentials = false;
            mailClient.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["UserName"].ToString(), ConfigurationManager.AppSettings["Password"].ToString());
            mailClient.Send(myMailMessage);
        }
        catch
        {

        }
    }

    protected void SignUp_Click(object sender, EventArgs e)
    {
        //see CustomValidator1_ServerValidate
    }

    protected void CustomValidator1_ServerValidate(object source, ServerValidateEventArgs args)
    {
        if (ValidateUser())
        {
            args.IsValid = true;
            SaveUser();
            SendMail();
            AccountMultiView.ActiveViewIndex = 1;
        }
        else
            args.IsValid = false;
    }
}
